### ISSUE TITLE
specify cpu time and memory limit

### ISSUE THREAD

**Issue by ndangtt** [sat-group/open-wbo#7]
Is there a way to specify cpu time and memory limit for open-wbo? I can't seem to find the corresponding command line argument from -help.

Thanks,

**Comment by conp-solutions** [comment]
Hi,There is currently not. The ability to do so in the SAT backend is not forwarded to the open-wbo CLI. I actually already thought about doing so, and have some local version that is capable of that. I will create a pull request.Best,Norbert

**Comment by ndangtt** [comment]
That is great. Thank you very much!
Best,
Nguyen

**Comment by rubengmartins** [comment]
Thanks @conp-solutions for creating a patch with the options to limit time and memory.

These can now be accessible with the options:
```
-cpu-lim      = <int32>  [   0 .. imax] (default: 0)

        Limit on CPU time allowed in seconds.

  -mem-lim      = <int32>  [   0 .. imax] (default: 0)

        Limit on memory usage in megabytes.
```

**Comment by ndangtt** [comment]
Thank you! I shall now close this issue.
